<?php
echo "
<style type='text/css'>
body
{
	font-family: Verdana, Arial, Helvetica, SansSerif;
	margin-top:0;
	margin-left:0;
	margin-right:0;
	margin-bottom:0;
	text-decoration: none;
}

.titreWhiteCenter {

	font-family: Arial, Helvetica, SansSerif;
	font-size: 11px;
	font-style: normal;
	color: #FFFFFF;
	text-align: center;
	font-weight: bold;
}


td, div, p, ul
{
	font-family: Verdana, Arial, Helvetica, SansSerif;
	font-size: 10px;
	text-decoration: none;
}

select.s1
{ 
	font-family: Verdana, Arial, Helvetica, SansSerif;
	color: #606E84;
	font-size: 10px;
	height: 16px;
	text-decoration: none;
	width: 100px

}

select.s2
{ 
	font-family: Verdana, Arial, Helvetica, SansSerif;
	color: #606E84;
	font-size: 10px;
	height: 16px;
	text-decoration: none;
	width: auto;

}


input.i1
{ 
	font-family: Verdana, Arial, Helvetica, SansSerif;
	font-style: italic;
	font-weight:normal;
  	background-color: #CCCCCC;
	font-size: 10px;
	height: 18px;
	text-decoration: none;
	text-align: right;
	width: auto;
}

input.i2
{ 
	font-family: Verdana, Arial, Helvetica, SansSerif;
	color: #606E84;
	font-size: 10px;
	padding: 2px;
	height: 18px;
	text-decoration: none;
	width: auto;
}

input.i3
{ 
	font-family: Verdana, Arial, Helvetica, SansSerif;
	font-style: italic;
	font-weight:normal;
  	background-color: #CCCCCC;
	font-size: 10px;
	height: 18px;
	text-decoration: none;
	text-align: right;
}

.ajout_submit {
	font-family: Arial, Helvetica, SansSerif;
	font-size: 10px;
	font-style: normal;
	color: #000000;
	text-align: center;
	font-weight: bold;
}
</style>";
?>
