<?php
	// Portion BODY
?>
<!-- body_text //-->
    <td width="100%" valign="top">
	<table border="0" width="100%" cellspacing="0" cellpadding="0">
      <tr>
        <td>
		  	<table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tr>
            <td><img src="gifs/pixel_trans.gif" border="0" alt="" width="100%" height="2"></td>
          </tr>
          <tr>
            <td>
        		<!-- Encadré //-->
		<table border="0" width="100%" cellspacing="0" cellpadding="0">
		  <tr>
			<td class="s_plan_b">
		      	  <?=$txt['Politique_confidentialite']?>
		        </td>
		  </tr>
		</table>

<table border="0" width="100%" cellspacing="0" cellpadding="1" class="infoBox">
	<tr>
		<td>
			<table border="0" width="100%" cellspacing="0" cellpadding="4" class="infoBoxContents">
				<tr>
					<td>

 <?php 
 if ($_SESSION['langue']=="fr"){ 
 ?>
	<blockquote> 
              <p class="normalTextBold"><br/>
                Politique en mati&egrave;re de protection des renseignements personnels des clients </p>
              <p class="normalText"><span class="normalTextBold"><?=$param['nom_client'];?></span> 
                s'est engag&eacute;e &agrave; prot&eacute;ger la confidentialit&eacute; 
                et la s&eacute;curit&eacute; des renseignements personnels obtenus 
                &agrave; l&#8217;occasion de ses relations commerciales avec la 
                client&egrave;le. La pr&eacute;sente politique explique les types 
                de renseignements personnels que nous recueillons et la mani&egrave;re 
                dont ils sont utilis&eacute;s. Nous abordons aussi les mesures 
                adopt&eacute;es pour s&#8217;assurer qu'ils soient trait&eacute;s 
                ad&eacute;quatement. </p>
              <p class="normalText">Les politiques et les pratiques mises de l&#8217;avant 
                sont &eacute;labor&eacute;es conform&eacute;ment &agrave; la Loi 
                sur la protection des renseignements personnels et les documents 
                &eacute;lectroniques (LPRP/DE) et &agrave; toute autre loi provinciale 
                correspondante sur la protection des renseignements personnels. 
                <br/>
                <br/>
                <span class="normalTextBold">Param&egrave;tres </span><br/>
                Les renseignements personnels sont des informations se rapportant 
                &agrave; une personne en particulier. Ils sont enregistr&eacute;s 
                sous diverses formes. Cela comprend des donn&eacute;es comme l'&acirc;ge 
                d'une personne, ses revenus, sa date de naissance, son origine 
                ethnique, son adresse, son num&eacute;ro de t&eacute;l&eacute;phone, 
                son adresse &eacute;lectronique, son dossier m&eacute;dical et 
                son dossier de cr&eacute;dit. Les informations au sujet d&#8217;une 
                personne qui sont contenues dans les documents suivants ne sont 
                toutefois pas consid&eacute;r&eacute;es comme des renseignements 
                personnels : </p>
              <ul>
                <li class="normalText">annuaires t&eacute;l&eacute;phoniques publics 
                  dans lesquels un abonn&eacute; peut refuser d'&ecirc;tre inscrit; 
                </li>
                <li class="normalText">r&eacute;pertoires professionnels et commerciaux, 
                  accessibles au public; </li>
                <li class="normalText">certains registres publics et dossiers 
                  de la cour; </li>
                <li><span class="normalText">certaines autres publications, imprim&eacute;es 
                  ou &eacute;lectroniques, accessibles au public</span>. </li>
              </ul>
              <p class="normalText">Notre engagement envers la protection de vos 
                renseignements personnels est r&eacute;gi par les principes suivants 
                :</p>
              <p class="normalText"><span class="normalTextBold">1. Nous sommes 
                responsables devant vous.</span><br/>
                <?=$param['nom_client'];?> est responsable de tous les renseignements personnels 
                qui sont sous son contr&ocirc;le, y compris tous les renseignements 
                personnels transf&eacute;r&eacute;s &agrave; une tierce partie 
                &agrave; des fins de traitement, de stockage ou autre. Dans chacune 
                de nos unit&eacute;s fonctionnelles, des employ&eacute;s sont 
                charg&eacute;s de s'assurer que nous nous conformons &agrave; 
                ces principes de confidentialit&eacute; et de s&eacute;curit&eacute; 
                en ce qui a trait &agrave; vos renseignements personnels. </p>
              <p class="normalText"><span class="normalTextBold">2. Nous vous 
                informons de la raison pour laquelle nous recueillons des renseignements 
                personnels.</span><br/>
                <?=$param['nom_client'];?> mentionne pourquoi elle recueille des renseignements 
                personnels, soit avant, soit pendant la collecte de ces renseignements.</p>
              <p class="normalText"><span class="normalTextBold">3. Nous obtenons 
                votre consentement pour la collecte, l'utilisation et la communication 
                de vos renseignements personnels.</span><br/>
                <?=$param['nom_client'];?> obtient votre consentement pour la collecte, 
                l'utilisation ou la communication de vos renseignements personnels. 
                La m&eacute;thode de cueillette des donn&eacute;es &agrave; laquelle 
                vous consentez varie en fonction du type de renseignements personnels 
                recueillis, utilis&eacute;s ou communiqu&eacute;s : </p>
              <ul>
                <li class="normalText"><?=$param['nom_client'];?> obtiendra votre consentement 
                  explicite (verbal, par &eacute;crit ou par voie &eacute;lectronique) 
                  pour la collecte, l'utilisation ou la communication de tout 
                  renseignement personnel de nature d&eacute;licate comme des 
                  renseignements financiers personnels. </li>
                <li> <span class="normalText"><?=$param['nom_client'];?> utilisera votre 
                  consentement implicite pour la collecte, l'utilisation ou la 
                  communication de vos renseignements personnels, lorsque l'une 
                  ou l'autre des conditions ci-dessous s'appliquent :</span> 
                  <ul>
                    <li class="normalText">une relation commerciale existe d&eacute;j&agrave;;</li>
                    <li class="normalText"> le consentement explicite a d&eacute;j&agrave; 
                      &eacute;t&eacute; obtenu;</li>
                    <li class="normalText"> la raison justifiant l'utilisation 
                      des renseignements personnels est raisonnablement &eacute;vidente 
                      pour vous.</li>
                  </ul>
                </li>
              </ul>
              <span class="normalText"> 
              <blockquote> 
                <p class="normalText">Vous pouvez modifier en tout temps vos pr&eacute;f&eacute;rences 
                  touchant votre consentement en communiquant avec le service 
                  &agrave; la client&egrave;le d&#8217;<?=$param['nom_client'];?>. Un repr&eacute;sentant 
                  acheminera votre appel aux autorit&eacute;s comp&eacute;tentes. 
                  Pour savoir comment modifier vos pr&eacute;f&eacute;rences, 
                  reportez-vous &agrave; la rubrique Modifier mon profil.</p>
              </blockquote>
              <p class="normalText"><strong>4. Nous limitons la collecte de vos 
                renseignements personnels.</strong><br/>
                <?=$param['nom_client'];?> recueille uniquement les renseignements n&eacute;cessaires 
                dans le but de pouvoir vous offrir ses produits et ses services. 
                Si ces informations personnelles dont nous avons besoin sont recueillies 
                pour une raison autre que celle de pouvoir vous offrir nos produits 
                et nos services, nous demanderons votre consentement soit avant, 
                soit pendant la collecte de ces renseignements. <?=$param['nom_client'];?> 
                recueillera des renseignements personnels uniquement en employant 
                des moyens clairs, justes et licites. </p>
              <p class="normalText">Exemples de raisons pour lesquelles nous recueillons 
                des renseignements personnels : </p>
              <blockquote> 
                <ul>
                  <li class="normalText">communication avec nos clients, en g&eacute;n&eacute;ral; 
                  </li>
                  <li class="normalText">traitement de vos demandes; </li>
                  <li class="normalText">traitement et suivi des transactions, 
                    et communication avec vous &agrave; ce sujet;</li>
                  <li class="normalText"> protection contre les fraudes et les 
                    erreurs; </li>
                  <li class="normalText">fourniture des produits et services que 
                    vous avez demand&eacute;s; </li>
                  <li class="normalText">recommandation de produits et services 
                    qui, selon <?=$param['nom_client'];?>, vous int&eacute;resseront ou 
                    vous offrent une valeur ajout&eacute;e; </li>
                  <li class="normalText">conformit&eacute; avec les prescriptions 
                    juridiques et exigences gouvernementales. </li>
                </ul>
              </blockquote>
              <p><span class="normalTextBold">5. Nous limitons l'utilisation, 
                la communication et la conservation de vos renseignements personnels.</span><span class="normalText"><br/>
                <?=$param['nom_client'];?> utilise et communique vos renseignements personnels 
                seulement aux fins pour lesquelles ils sont recueillis. <?=$param['nom_client'];?> 
                ne vend ni ne loue vos renseignements personnels &agrave; aucun 
                organisme ni &agrave; aucune personne, &agrave; quelque fin que 
                ce soit. </span></p>
              <p class="normalText">Nous ne communiquons vos renseignements personnels 
                &agrave; aucune tierce partie, sauf dans le but de vous offrir 
                des produits et des services. Si nous communiquons vos renseignements 
                personnels &agrave; une tierce partie, cette derni&egrave;re est 
                li&eacute;e &agrave; <?=$param['nom_client'];?> par les ententes n&eacute;cessaires 
                afin de prot&eacute;ger la confidentialit&eacute; et la s&eacute;curit&eacute; 
                de vos renseignements personnels. <?=$param['nom_client'];?> ne conserve 
                vos renseignements personnels que tant qu'ils sont requis pour 
                nos relations commerciales ou selon les exigences qui sont stipul&eacute;es 
                par les lois f&eacute;d&eacute;rales et provinciales (Canada).</p>
              <p><span class="normalTextBold">6. Nous gardons vos renseignements 
                personnels &agrave; jour et exacts. </span><span class="normalText"><br/>
                <?=$param['nom_client'];?> garde vos renseignements personnels &agrave; 
                jour, exacts et pertinents en fonction de leur utilisation pr&eacute;vue. 
                </span></p>
              <p class="normalText">Vous pouvez demander d'avoir acc&egrave;s 
                aux renseignements personnels d&eacute;tenus &agrave; votre sujet 
                dans nos dossiers afin de pouvoir les consulter et les modifier 
                au besoin. Dans l&#8217;&eacute;ventualit&eacute; o&ugrave; vos 
                renseignements personnels nous sont fournis par une tierce partie, 
                nous vous adresserions &agrave; celle-ci (ex : une agence d'&eacute;valuation 
                du cr&eacute;dit). Pour savoir comment acc&eacute;der &agrave; 
                vos renseignements personnels, reportez-vous &agrave; la rubrique 
                Modifier mon profil. </p>
              <p><span class="normalTextBold">7. La s&eacute;curit&eacute; de 
                vos renseignements personnels constitue une priorit&eacute; 
                pour <?=$param['nom_client'];?>. </span><span class="normalText"><br/>
                Nous prenons des mesures strictes pour prot&eacute;ger vos renseignements 
                personnels, peu importe le format dans lequel nous les d&eacute;tenons, 
                entre autres :</span></p>
              <ul>
                <li class="normalText">mesures de s&eacute;curit&eacute; physique, 
                  telles que des bureaux &agrave; acc&egrave;s contr&ocirc;l&eacute; 
                  et des </li>
                <li class="normalText">classeurs verrouill&eacute;s;</li>
                <li><span class="normalText"> mesures de s&eacute;curit&eacute; 
                  &eacute;lectronique pour les renseignements </span><span class="normalText">personnels 
                  informatis&eacute;s <br/>
                  comme la protection par mot de passe, le cryptage des bases 
                  de donn&eacute;es et les num&eacute;ros d'identification personnels;</span></li>
                <li><span class="normalText"> processus organisationnels tels 
                  que la restriction de l'acc&egrave;s &agrave; vos renseignements 
                  </span><span class="normalText">personnels &agrave; un groupe 
                  s&eacute;lectionn&eacute; de personnes;</span></li>
                <li class="normalText"> obligations contractuelles avec les tierces 
                  parties qui doivent avoir acc&egrave;s &agrave; vos renseignements 
                  personnels, les obligeant &agrave; prot&eacute;ger la confidentialit&eacute; 
                  et la s&eacute;curit&eacute; de vos renseignements personnels. 
                </li>
              </ul>
              <p><span class="normalTextBold">8. Nous sommes ouverts &agrave; 
                propos de notre politique en mati&egrave;re de 
                protection des renseignements personnels. </span><span class="normalText"><br/>
                Nous nous sommes engag&eacute;s &agrave; vous offrir de l'information 
                compr&eacute;hensible et facilement accessible au sujet de nos 
                politiques et de nos pratiques en mati&egrave;re de gestion de 
                vos renseignements personnels. Cette disposition et tout renseignement 
                connexe sont accessibles en tout temps sur notre site Web sous 
                Politique de confidentialit&eacute; ou sur demande. </span></p>
              <p><span class="normalTextBold">9. Vous avez acc&egrave;s &agrave; 
                vos renseignements personnels conserv&eacute;s chez 
                <?=$param['nom_client'];?>. </span><span class="normalText"><br/>
                Vous pouvez demander d'avoir acc&egrave;s &agrave; vos renseignements 
                personnels qui sont conserv&eacute;s chez <?=$param['nom_client'];?>. Pour 
                savoir comment communiquer avec nous, reportez-vous &agrave; la 
                rubrique Service &agrave; la client&egrave;le. D&egrave;s r&eacute;ception 
                d'une telle demande, <?=$param['nom_client'];?> : </span></p>
              <ul>
                <li class="normalText">vous informera du type de renseignements 
                  personnels que nous avons dans nos dossiers ou sous notre contr&ocirc;le, 
                  comment ceux-ci sont utilis&eacute;s et &agrave; qui ils pourraient 
                  avoir &eacute;t&eacute; communiqu&eacute;s; </li>
                <li class="normalText">vous donnera acc&egrave;s &agrave; ces 
                  renseignements, afin que vous puissiez les consulter, en v&eacute;rifier 
                  l'exactitude et l'int&eacute;gralit&eacute; et demander de les 
                  modifier, au besoin; </li>
                <li class="normalText">apportera toute mise &agrave; jour n&eacute;cessaire 
                  &agrave; vos renseignements personnels. </li>
              </ul>
              <p><span class="normalTextBold"><br/>
                10. Nous r&eacute;pondons &agrave; vos questions, vos inqui&eacute;tudes 
                et vos plaintes en mati&egrave;re de protection des renseignements personnels. </span> 
                <span class="normalText"><br/>
                <?=$param['nom_client'];?> r&eacute;pond promptement &agrave; toutes vos 
                questions, vos inqui&eacute;tudes et vos plaintes concernant la 
                confidentialit&eacute; et la s&eacute;curit&eacute; de vos renseignements 
                personnels et nos politiques et m&eacute;thodes en mati&egrave;re&nbsp;de 
                protection des renseignements personnels. </span></p>
              <p class="normalTextBold">Pour communiquer avec nous </p>
<?php
} else if ($_SESSION['langue']=="en"){
?>
	<blockquote> 
              <p><span class="normalTextBold">Politics regarding the protection 
                of personal information of customers. </span><span class="normalText"><br/>
                </span><span class="normalTextBold"><?=$param['nom_client'];?></span><span class="normalText"> 
                commits to protect the confidentiality and the security of the 
                personal information obtained at the moment of the commercial 
                relationships with their customers. The present politics explains 
                the types of personal information to which we refer and the way 
                in that it is used. We also approach the measures adopted to assure 
                that they are treated appropriately. <br/>
                <br/>
                The politics and the considered practices are elaborated according 
                to the Law on the protection of the personal information and the 
                electronic documents (LPRD/DE) and to all corresponding to other 
                provincial law regarding the protection of personal information. 
                <br/>
                <br/>
                </span><span class="normalTextBold"><br/>
                Parameters </span><span class="normalText"><br/>
                The personal information is the data that corresponds to a person 
                in particular. This data is registered in diverse ways. Here is 
                included data like the age of a person, their revenues, their 
                date of birth, their ethnic origin, their address, their telephone 
                number, their electronic mail address, their medical file and 
                their credit history. The information referred to a person included 
                in the following documents is not considered as personal information: 
                </span></p>
              <ul>
                <li><span class="normalText">public directory phone in which a 
                  subscriber can refuse to be subscribed. </span></li>
                <li><span class="normalText">professional and commercial directories, 
                  accessible to the public. </span></li>
                <li><span class="normalText">certain public registrations and 
                  files of the court. </span></li>
                <li><span class="normalText">other certain accessible publications, 
                  printed or electronic, to the public. </span></li>
              </ul>
              <p><span class="normalText">Our commitment with the protection of 
                its personal information is governed by the following principles: 
                <br/>
                <br/>
                </span><span class="normalTextBold">1. We are responsible before 
                you.</span><span class="normalText"> <br/>
                An</span><span class="normalTextBold">tillas-Express</span><span class="normalText"> 
                it is responsible for all the personal information that is under 
                its control, including the information transferred to third parties 
                in order to treatment, storage or other processes. In each one 
                of our functional units, the employees take in charge the assurance 
                that we act according to these principles of confidentiality and 
                of security as for the treatment of their personal information. 
                <br/>
                <br/>
                <br/>
                </span><span class="normalTextBold">2. We inform you the reason 
                for which we request your personal data. </span><span class="normalText"><br/>
                <?=$param['nom_client'];?> mentions the reasons to gather their personal 
                information, before and during the moment of been registered. 
                <br/>
                <br/>
                </span><span class="normalTextBold">3. We obtain your consent 
                for the registration, use and communication of your personal data. 
                <br/>
                <?=$param['nom_client'];?></span><span class="normalText"> will ask for 
                your consent to gather, to use or to communicate your personal 
                data. The method of collecting the data that you consent may vary 
                in function of the type of the registered, used or communicated 
                personal information: </span></p>
              <ul>
                <li><span class="normalTextBold"><?=$param['nom_client'];?></span><span class="normalText"> 
                  will obtain your explicit consent (verbal, written or electronic) 
                  for the gathering, the use or communication of all personal 
                  fact of delicate nature as personal financial states.</span></li>
                <li><span class="normalTextBold"><?=$param['nom_client'];?></span><span class="normalText"> 
                  will use your explicit consent for the collection, the use or 
                  communication of your personal data when some of the following 
                  conditions are applied: </span> 
                  <blockquote> 
                    <p class="normalText">- a commercial relationship that already 
                      exists; <br/>
                      - the explicit consent has already been obtained; <br/>
                      - the reason that justifies the use of its personal data 
                      is reasonably evident for you. </p>
                  </blockquote>
                </li>
              </ul>
              <p><span class="normalText">You can modify in all time your preferences 
                as for your consent communicating with the customer service of 
                <?=$param['nom_client'];?>. A representative will guide your call to the 
                competent authorities. To know how to modify your preferences 
                please refer to Modify my profile. <br/>
                <br/>
                </span><span class="normalTextBold">4. We limit the gathering 
                of your personal data. </span><span class="normalText"><br/>
                </span><span class="normalTextBold"><?=$param['nom_client'];?></span><span class="normalText"> 
                only gathers the necessary data in order to offer their products 
                and services. If that necessary personal information was gathered 
                for some other objective that was not the one of offering our 
                products and services, we will demand your consent, before or 
                during the gathering. Ant</span><span class="normalTextBold">illas-Express</span><span class="normalText"> 
                will gather the personal information using clear, fair and licit 
                means. <br/>
                <br/>
                Example of reasons for which we gather your personal information: 
                </span></p>
              <ul>
                <li><span class="normalText">communication with our customers, 
                  in general; </span></li>
                <li><span class="normalText">treatment of your applications; </span></li>
                <li><span class="normalText">treatment and pursuit of your transactions, 
                  and communication to you; </span></li>
                <li><span class="normalText">protection against the frauds and 
                  errors; </span></li>
                <li><span class="normalText">offer of products and services that 
                  were requested to us; </span></li>
                <li><span class="normalText">recommendation of products and services 
                  that, according to <?=$param['nom_client'];?>, they can interest you or 
                  may offer you an added value; </span></li>
                <li><span class="normalText">conformity with the juridical prescriptions 
                  and government demands. </span></li>
              </ul>
              <p><span class="normalTextBold">5. We limit the use, communication 
                and conservation of your personal data.</span><span class="normalText"><br/>
                </span><span class="normalTextBold"><?=$param['nom_client'];?></span><span class="normalText"> 
                uses and only communicates your personal data with the purposes 
                for which were gathered. <?=$param['nom_client'];?> doesn't sell neither 
                it leases your personal data to any organism neither another person, 
                for the no reason. <br/>
                <br/>
                We don't communicate your personal data to any third part. We 
                only save it in order to offering you the products or services. 
                If we communicate your personal information to a third part, this 
                last one is bound to <?=$param['nom_client'];?> for the necessary link in 
                order to protect the confidentiality and the security of your 
                personal information. <?=$param['nom_client'];?> doesn't conserve their 
                personal data for other ends that those required for the commercial 
                relationships or according to the demands that are specified by 
                the federal and provincial laws (Canada). </span></p>
              <p> <span class="normalTextBold">6. We keep your personal data exact 
                and up-to-date.<br/>
                </span><span class="normalText"><?=$param['nom_client'];?> keeps exactly 
                and up-to-date your pertinent personal data in function of the 
                use accorded. You can request of having access to your personal 
                information retained in your file in order to consult and to modify 
                them according to your needs. In the case of the eventuality that 
                your data were provided to a third part, we will refer to it. 
                (example: agent of credit evaluation). To know the way to consent 
                to your personal data, go to Modify my profile. <br/>
                </span><span class="normalTextBold"><br/>
                7. The security of your personal data constitutes a priority for 
                <?=$param['nom_client'];?>. </span><span class="normalText"><br/>
                We take strict measures to protect your personal data, without 
                caring the format in which they are registered, like: </span></p>
              <ul>
                <li><span class="normalText">measures of physical security, such 
                  as classifiers and files with locks and access control; </span></li>
                <li><span class="normalText">measures of electronic security to 
                  keep your computerized data protected such as the protection 
                  by means of access key, the encryption of the databases and 
                  personal identification numbers; </span></li>
                <li><span class="normalText">secured organizational processes 
                  like access restriction to your personal data and that for a 
                  selected group of people; </span></li>
                <li><span class="normalText">contractual obligations with third 
                  parts forcing them to protect the confidentiality and the security 
                  of your personal data. </span></li>
              </ul>
              <p><span class="normalTextBold">8. We&#8217;re transparent in our 
                politics regarding the protection of your personal data. </span><span class="normalText"><br/>
                We commit to offer comprehensible and easily accessible information 
                on our politics and our practices as regards administration of 
                your personal data. This disposition and all related fact are 
                accessible in all time on our site under Politics of confidentiality. 
                <br/>
                <br/>
                </span><span class="normalTextBold">9. You have access to your 
                own personal data conserved in <?=$param['nom_client'];?>. </span><span class="normalText"><br/>
                You can request to have access to your personal data that is conserved 
                in <?=$param['nom_client'];?>. To know how to communicate with us, go to 
                Customer Service. After receiving such a demand, <?=$param['nom_client'];?> 
                will proceed this way: </span></p>
              <ul>
                <li><span class="normalText">We will inform you of the type of 
                  personal data that we have in our files or under our control, 
                  how they can be used or to whom it could be communicated. </span></li>
                <li><span class="normalText">We will give access to those data 
                  with the end that you could consult them to verify the accuracy 
                  and integrity, and to request their modification as needed. 
                  </span></li>
                <li><span class="normalText">We will contribute to all necessary 
                  upgrade within your personal data. </span></li>
              </ul>
              <p><span class="normalTextBold">10. We respond to your questions 
                doubts and complain as regards protection of your personal data. 
                </span><span class="normalText"><br/>
                </span><span class="normalTextBold"><?=$param['nom_client'];?></span><span class="normalText"> 
                responds appropriately to all your questions, doubts and complains 
                concerning the confidentiality and the security of your personal 
                data and our politics and methods as regards protection of personal 
                data. <br/>
                <br/>
                </span><span class="normalTextBold">To communicate with us </span><span class="normalText"><br/>
<?} else {?>
				<blockquote> 
              <p class="normalTextBold"><br/>
                Pol&iacute;tica en materia de protecci&oacute;n de la informaci&oacute;n 
                personal de los clientes.</p>
              <p class="normalText"><span class="normalTextBold"><?=$param['nom_client'];?></span> 
                se compromete a proteger la confidencialidad y la seguridad de 
                la informaci&oacute;n personal obtenida en ocasi&oacute;n de las 
                relaciones comerciales con sus clientes. La presente pol&iacute;tica 
                explica los tipos de informaci&oacute;n personal a la cual nos 
                referimos y la manera en que es utilizada. Abordamos tambi&eacute;n 
                las medidas adoptadas para asegurar que son tratados adecuadamente.<br/>
                <br/>
                Las pol&iacute;ticas y las pr&aacute;cticas consideradas son elaboradas 
                conforme a la Ley sobre la protecci&oacute;n de la informaci&oacute;n 
                personal y los documentos electr&oacute;nicos (LPRD/DE) y a toda 
                otra ley provincial correspondientes obre la protecci&oacute;n 
                del a informaci&oacute;n personal.<br/>
                <br/>
                <span class="normalTextBold"><br/>
                Par&aacute;metros</span><span class="normalText"><br/>
                </span>La informaci&oacute;n personal es la informaci&oacute;n 
                que corresponde a una persona en particular. Estos datos son registrados 
                de diversas formas. Ellos comprenden los datos como la edad de 
                una persona, sus ingresos, su fecha de nacimiento, su origen &eacute;tnico, 
                su domicilio, su n&uacute;mero de tel&eacute;fono, su direcci&oacute;n 
                de correo electr&oacute;nico, su archivo m&eacute;dico y su historia 
                de cr&eacute;dito. La informaci&oacute;n referida a una persona 
                incluida en los documentos siguientes no son consideradas como 
                informaci&oacute;n personal:</p>
              <ul>
                <li class="normalText">directorios telef&oacute;nicos p&uacute;blicos 
                  en los cuales un abonado puede negarse a ser inscripto.</li>
                <li class="normalText"> directorios profesionales y comerciales, 
                  accesibles al p&uacute;blico.</li>
                <li class="normalText"> ciertos registros p&uacute;blicos y archivos 
                  de la corte.</li>
                <li class="normalText"> otras ciertas publicaciones, impresas 
                  o electr&oacute;nicas, accesibles al p&uacute;blico.</li>
              </ul>
              <p class="normalText">Nuestro compromiso con la protecci&oacute;n 
                de su informaci&oacute;n personal est&aacute; regido por los siguientes 
                principios :</p>
              <p class="normalText"><span class="normalTextBold">1. Nosotros somos 
                responsables ante usted.</span><br/>
                <?=$param['nom_client'];?> es responsable de toda la informaci&oacute;n 
                personal que est&eacute; bajo su control, incluyendo la informaci&oacute;n 
                transferida a terceras partes a fin de tratamiento, almacenamiento 
                u otro. En cada una de nuestras unidades funcionales, los empleados 
                son encargados de asegurar que nosotros actuemos conforme a estos 
                principios de confidencialidad y de seguridad en cuanto al tratamiento 
                de su informaci&oacute;n personal.</p>
              <p class="normalText"><span class="normalTextBold">2. Nosotros le 
                informamos la raz&oacute;n por la cual le solicitamos sus datos 
                personales.</span><br/>
                <?=$param['nom_client'];?> menciona las razones para recolectar su informaci&oacute;n 
                personal, tanto sea antes como durante el momento de registrarlos.</p>
              <p class="normalText"><span class="normalTextBold">3. Nosotros obtenemos 
                su consentimiento para el registro, la utilizaci&oacute;n y comunicaci&oacute;n 
                de sus datos personales.</span><br/>
                <?=$param['nom_client'];?> obtiene su consentimiento para recolectar, utilizar 
                o comunicar sus datos personales. El m&eacute;todo de colectar 
                los datos que usted consiente, var&iacute;an en funci&oacute;n 
                del tipo de la informaci&oacute;n personal registrada, utilizada 
                o comunicada :</p>
              <ul>
                <li class="normalText"> <?=$param['nom_client'];?> obtendr&aacute; vuestro 
                  consentimiento expl&iacute;cito (verbal, escrito o por v&iacute;a 
                  electr&oacute;nica) para la recolecci&oacute;n, la utilizaci&oacute;n 
                  ola comunicaci&oacute;n de todo dato personal de naturaleza 
                  delicada como estados financieros personales.</li>
                <li><span class="normalText"> <?=$param['nom_client'];?> utilizar&aacute; 
                  vuestro consentimiento expl&iacute;cito para la colecta, la 
                  utilizaci&oacute;n ola comunicaci&oacute;n de sus datos personales 
                  cuando se aplique alguna de las condiciones siguientes: </span> 
                  <blockquote> 
                    <p class="normalText">- una relaci&oacute;n comercial ya existe;<br/>
                      - el consentimiento expl&iacute;cito ya ha sido obtenido;<br/>
                      - la raz&oacute;n que justifica la utilizaci&oacute;n de 
                      sus datos personales es razonablemente evidente para usted.</p>
                  </blockquote>
                </li>
              </ul>
              <p class="normalText">Usted puede modificar en todo tiempo sus preferencias 
                en cuanto a su consentimiento comunic&aacute;ndose con el servicio 
                a la clientela de <?=$param['nom_client'];?>. Un representante encaminar&aacute; 
                su llamada a las autoridades competentes. Para conocer c&oacute;mo 
                modificar sus preferencias refi&eacute;rase a Modificar mi perfil.</p>
              <p class="normalText"><span class="normalTextBold">4. Nosotros limitamos 
                la recolecci&oacute;n de sus datos personales.</span><br/>
                <?=$param['nom_client'];?> recolecta &uacute;nicamente los datos necesarios 
                con el objeto de poder ofrecer sus productos y servicios. Si esa 
                informaci&oacute;n personal de la cual tenemos necesidad, fueran 
                recolectadas para alg&uacute;n otro objetivo que no fuera el de 
                brindar nuestros productos y servicios, demandaremos su consentimiento, 
                tanto sea antes como durante la recolecci&oacute;n. <?=$param['nom_client'];?> 
                recolectar&aacute; la informaci&oacute;n personal empleando medios 
                claros, justos y l&iacute;citos.</p>
              <p class="normalText">Ejemplo de razones por las cuales recolectamos 
                su informaci&oacute;n personal:</p>
              <ul>
                <li class="normalText"> comunicaci&oacute;n con nuestros clientes, 
                  en general;</li>
                <li class="normalText"> tratamiento de sus solicitudes;</li>
                <li class="normalText"> tratamiento y seguimiento de las transacciones, 
                  y comunicaci&oacute;n a ese sujeto;</li>
                <li class="normalText"> protecci&oacute;n contra los fraudes y 
                  los errores;<br/>
                  despacho de productos y servicios que nos haya solicitado;</li>
                <li class="normalText"> recomendaci&oacute;n de productos y servicios 
                  que, seg&uacute;n <?=$param['nom_client'];?>, le puedan interesar o le 
                  ofrezcan un valor agregado;</li>
                <li class="normalText"> conformidad con las prescripciones jur&iacute;dicas 
                  y exigencias gubernamentales.</li>
              </ul>
              <p class="normalText"><span class="normalTextBold">5. Limitamos 
                la utilizaci&oacute;n, la comunicaci&oacute;n y la conservaci&oacute;n 
                de sus datos personales.</span><br/>
                <?=$param['nom_client'];?> utiliza y comunica sus datos personales solamente 
                con los fines para los cuales fueron recolectados. <?=$param['nom_client'];?> 
                no vende ni arrienda sus datos personales a ning&uacute;n organismo 
                ni a otra persona, por la raz&oacute;n que sea.</p>
              <p class="normalText">No comunicamos sus datos personales a ninguna 
                tercera parte, salvo con el objeto de ofrecerle productos o servicios. 
                Si comunicamos su informaci&oacute;n personal a una tercera parte, 
                esta &uacute;ltima est&aacute; ligada a <?=$param['nom_client'];?> por los 
                lazos necesarios a fin de proteger la confidencialidad y la seguridad 
                de su informaci&oacute;n personal. <?=$param['nom_client'];?> no conserva 
                sus datos personales para otros fines que aquellos requeridos 
                para las relaciones comerciales o seg&uacute;n las exigencias 
                que son estipuladas por las leyes federales y provinciales (Canada).</p>
              <p class="normalText"><span class="normalTextBold">6. Guardamos 
                sus datos personales actualizados y exactos. </span><br/>
                <?=$param['nom_client'];?> guarda sus datos personales actualizados, exactos 
                y pertinentes en funci&oacute;n de su utilizaci&oacute;n prevista.<br/>
                Usted puede solicitar de tener acceso a su informaci&oacute;n 
                personal retenida en su archivo a fin de poder consultar y modificarlos 
                seg&uacute;n sus necesidades. Ante la eventualidad que sus datos 
                fuesen prove&iacute;dos por una tercera parte, nosotros nos dirigiremos 
                a &eacute;sta (ejemplo: agente de evaluaci&oacute;n de cr&eacute;dito). 
                Para conocer la manera de acceder a sus datos personales, dir&iacute;jase 
                a Modificar mi perfil.</p>
              <p class="normalText"><span class="normalTextBold">7. La seguridad 
                de sus datos personales constituye una prioridad para <?=$param['nom_client'];?>.</span><br/>
                Tomamos medidas estrictas para proteger sus datos personales, 
                sin importar el formato en el cual est&eacute;n registrados, entre 
                otras:</p>
              <ul>
                <li class="normalText">medidas de seguridad f&iacute;sica, tal 
                  que archiveros de acceso controlado y clasificadores con trancas;</li>
                <li class="normalText"> medidas de seguridad electr&oacute;nicas 
                  paral os datos personales informatizados como la protecci&oacute;n 
                  mediante clave de acceso, el encriptado de las bases de datos 
                  y n&uacute;meros de identificaci&oacute;n personales;</li>
                <li class="normalText"> procesos organizacionales tales que la 
                  restricci&oacute;n de acceso a sus datos personales a un grupo 
                  seleccionado de personas;</li>
                <li><span class="normalText"> obligaciones contractuales con terceras 
                  partes que deben acceder a sus datos personales, oblig&aacute;ndolos 
                  a proteger la confidencialidad y la seguridad de sus datos personales. 
                  </span> </li>
              </ul>
              <p class="normalText"><span class="normalTextBold">8. Somos transparentes 
                en relaci&oacute;n a nuestra pol&iacute;tica en materia de protecci&oacute;n 
                de sus datos personales.</span><br/>
                Nos comprometemos a ofrecerle informaci&oacute;n comprensible 
                y f&aacute;cilmente accesible sobre nuestras pol&iacute;ticas 
                y nuestras pr&aacute;cticas en materia de gesti&oacute;n de sus 
                datos personales. Esta disposici&oacute;n y todo dato conexo son 
                accesibles en todo tiempo sobre nuestro sitio Web bajo Pol&iacute;tica 
                de confidencialidad, o a pedido.</p>
              <p class="normalText"><span class="normalTextBold">9. Usted tiene 
                acceso a sus datos personales conservados en <?=$param['nom_client'];?>.</span><br/>
                Usted puede solicitar tener acceso a sus datos personales que 
                son conservados en <?=$param['nom_client'];?>. Para saber c&oacute;mo comunicarse 
                con nosotros, dir&iacute;jase al Servicio a la clientela. Ante 
                la recepci&oacute;n de una tal demanda, <?=$param['nom_client'];?> :</p>
              <ul>
                <li class="normalText">Le informar&aacute; del tipo de dato personal 
                  que tenemos en nuestros archivos o bajo nuestro control, c&oacute;mo 
                  pueden ser utilizados o a quien podr&iacute;an ser comunicados.</li>
                <li class="normalText"> Le dar&aacute; acceso a esos datos con 
                  el fin que pudiera consultarlos para verificar la exactitud 
                  e integridad, y solicitar su modificaci&oacute;n en caso necesario.</li>
                <li class="normalText">Aportar&aacute; toda actualizaci&oacute;n 
                  necesaria a sus datos personales.</li>
              </ul>
              <p><span class="normalTextBold">10. Respondemos a sus preguntas, 
                inquietudes y reclamos en materia de protecci&oacute;n de sus 
                datos personales.</span><br/>
                <span class="normalText"><?=$param['nom_client'];?> responde apropiadamente 
                a todas sus preguntas, inquietudes y reclamos concerniente a la 
                confidencialidad y la seguridad de sus datos personales y nuestras 
                pol&iacute;ticas y m&eacute;todos en materia de protecci&oacute;n 
                de datos personales.</span><span class="normalText"> </span></p>
              <blockquote>
                <p class="normalTextBold">Para comunicarse con nosotros </p>
<?php
}
?>
                <p><span class="normalTextBold"><?=$txt['form_telephone'];?> :</span><span class="normalText"> 
                   <?=$param['telephone_client'];?><br/>
                  </span></p>
              </blockquote>
            </blockquote>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<!-- encadré_eof //-->
				</td>
          </tr>
          <tr>
            <td><img src="gifs/pixel_trans.gif" border="0" alt="" width="80%" height="10"></td>
          </tr>
        </table>
		  </td>
      </tr>
    </table>
	</td>
<!-- body_text_eof //-->