<?php
	/* Programme : ContactOK.inc
    * Description : Ecran de confirmation d'ajout d'un contact
    */
?>
<table width="100%" height="100%" border="0" cellspacing="0" cellpadding="0">
	<tr>
   	<td align="center" valign="top">
      	<p style="margin-top: 10pt">
         <p align="center" valign="bottom"><font size="+2">
         VOTRE INFORMATION A ÉTÉ REÇU AVEC SUCCÈS.<br>
         SON NUMÉRO EST LE</font><br>
		 <font size="+4"><?php echo $NoCon ?></font><br>
         </p>
      </td>
   </tr>
</table>
