<?php
?>
<div id="Gauche">
  <div id="logo">
  	<img src='gifs/logo.gif' width="220" height="189" alt='<?=$txt['TitreWeb']?>' />
	  <a href="suspect.php"><img src="gifs/blank.gif" width="1" height="1" border="0"></a>
  </div>
  <div id="nouschoisir">
  	<table border='0' cellpadding='4px' >
  		<tr>
  			<td align='right'>
  				<img id="fleche" src='gifs/fleche.gif' width="32" height="33" />
  			</td>
  			<td>
  				<h1>POURQUOI NOUS CHOISIR?</h1>
  			</td>
  		</tr>
 		<tr>
   			<td align='right'>
   				<span class="titreright">01</span>
  			</td>
  			<td>
  				<span class="hiTextRed">Un chef de file depuis 24 ans</span>
  			</td>
  		</tr>
 		<tr>
   			<td align='right'>&nbsp;
   				
  			</td>
  			<td>
  				<span >Cosat a commencé ses opérations à St-Jérôme en 1993. C'est en 2000 que le département 
				  informatique a été ajouté. Nous y effectuons la vente et la réparation d'ordinateur. Donc à St-Jérôme dans les Laurentides, cela fait 26 ans que Cosat vous offre des services informatique de 
				  qualité.</span>
  			</td>
  		</tr>
  		<tr>
   			<td align='right'>
   				<span class="titreright">02</span>
  			</td>
  			<td>
  				<span class="hiTextRed">Une solide expertise</span>
  			</td>
  		</tr>
  		<tr>
   			<td align='right'>&nbsp;
   				
  			</td>
  			<td>
  				<span >Denis Léveillé, votre conseiller, possède une expertise de plus de 32 ans dans le domaine de la vente d'ordinateur, de la réparation et
				   de l'entretien des ordinateurs personnels à St-Jérôme, Montréal et les environs</span>
  			</td>
  		</tr>
 	</table>
  </div>
  <div id="notremarque">
  	<table border='0' cellpadding='4px' >
  		<tr>
  			<td align='right'>
  				<img id="fleche" src='gifs/fleche.gif' width="32" height="33" />
  			</td>
  			<td>
  				<h1>NOTRE MARQUE</h1>
  			</td>
  		</tr>
 		<tr>
   			<td align='right'>&nbsp;
   				
  			</td>
  			<td>
  				<span >Nous assemblons nos ordinateurs sur place selon <b>vos spécifications</b>. Nous vous offrons un produit sur mesure rien
				  de moins. Notre méthode vous assure un produit adéquat qui répond à <b>VOS besoins</b>.</span>
  			</td>
  		</tr>
  		<tr>
   			<td align='right'>
   				<img src='gifs/ptfleche.gif' width="22" height="17" />
  			</td>
  			<td>
  				<span class="hiTextGreen"><a href="produit_detail.php?cat=&id=2">La marque Cosat</a></span>
  			</td>
  		</tr>
  		<tr>
  			<td align='right'>
  				<img id="fleche" src='gifs/fleche.gif' width="32" height="33" />
  			</td>
  			<td>
  				<h1>NOTRE ATELIER</h1>
  			</td>
  		</tr>
 		<tr>
   			<td align='right'>&nbsp;   				
  			</td>
  			<td>
  				<span >Nous effectuons la réparation d'ordinateurs sur place</b>. Vous aurez toujours un estimer des 
				  frais de réparations de votre ordinateur avant tout. Votre satisfaction grâce à un service de 
				  réparation d'ordinateur rapide et abordable est notre but ultime.</b>.</span>
  			</td>
  		</tr>
  		<tr>
   			<td align='right'>
   				<img src='gifs/ptfleche.gif' width="22" height="17" />
  			</td>
  			<td>
  				<span class="hiTextGreen"><a href="services.php">Le service Cosat</a></span>
  			</td>
  		</tr>
 	</table>
  </div>
</div>
<!--end navbar -->
