<?php
?>
<div id="Gauche">
  <div id="logo">
  	<img src='gifs/logo.gif' width="220" height="189" alt='<?=$txt['TitreWeb']?>' />
	  <a href="suspect.php"><img src="gifs/blank.gif" width="1" height="1" border="0"></a>
  </div>
  <div id="nouschoisir">
  	<table border='0' cellpadding='4px' >
  		<tr>
  			<td align='right'>
  				<img id="fleche" src='gifs/fleche.gif' width="32" height="33" />
  			</td>
  			<td>
  				<h1>POURQUOI NOUS CHOISIR?</h1>
  			</td>
  		</tr>
 		<tr>
   			<td align='right'>
   				<span class="titreright">01</span>
  			</td>
  			<td>
  				<span class="hiTextRed">Un chef de file depuis 20 ans</span>
  			</td>
  		</tr>
 		<tr>
   			<td align='right'>&nbsp;
   				
  			</td>
  			<td>
  				<span >Cosat a commenc&#233; ses op&#233;rations à St-J&#233;r&#244;me en 1989. C'est en 2000 que le d&#233;partement 
				  informatique a &#233;t&#233; ajout&#233;. Donc à St-J&#233;r&#244;me dans les Laurentides, cela fait 20 ans que Cosat vous offre 
				  des services informatique de qualit&#233;.</span>
  			</td>
  		</tr>
  		<tr>
   			<td align='right'>
   				<span class="titreright">02</span>
  			</td>
  			<td>
  				<span class="hiTextRed">Une solide expertise</span>
  			</td>
  		</tr>
  		<tr>
   			<td align='right'>&nbsp;
   				
  			</td>
  			<td>
  				<span >Une expertise de plus de 22 ans dans le domaine de la vente, de la r&#233;paration et
				   de l'entretien des ordinateurs personnels &#224; St-J&#233;r&#244;me</span>
  			</td>
  		</tr>
 	</table>
  </div>
  <div id="notremarque">
  	<table border='0' cellpadding='4px' >
  		<tr>
  			<td align='right'>
  				<img id="fleche" src='gifs/fleche.gif' width="32" height="33" />
  			</td>
  			<td>
  				<h1>NOTRE MARQUE</h1>
  			</td>
  		</tr>
 		<tr>
   			<td align='right'>&nbsp;
   				
  			</td>
  			<td>
  				<span >Nous assemblons nos ordinateurs sur place selon <b>vos sp&#233;cifications</b>. Nous vous offrons un produit sur mesure rien
				  de moins. Notre m&#233;thode vous assure un produit ad&#233;quat qui r&#233;pond &#224; <b>VOS besoins</b>.</span>
  			</td>
  		</tr>
  		<tr>
   			<td align='right'>
   				<img src='gifs/ptfleche.gif' width="22" height="17" />
  			</td>
  			<td>
  				<span class="hiTextGreen">La marque Cosat</span>
  			</td>
  		</tr>
 	</table>
  </div>
</div>
<!--end navbar -->
