<?php
// Avant 30 - 70 %  
?>
  <div id="produits">
  	<div class="produits_text">
  		<table>
  			<tr>
  				<td width=20% >
  				<span class="produits_img">
				  <img src='images/img_pc.jpg' alt='réparation, reparation, entretien, vente, ordinateur, informatique, saint-jerome, st-jerome, saint-jérôme, st-jérôme' width="123" height="141" align="left" />
				</span>
				</td>
				<td width=80%>

				<span class="GrosTexte"><center>ESSAYEZ NOTRE TECHNOLOGIE!!!</center></span>
   				<center>
   				Chez <?=@$param['nom_client'];?><br>
   		  		Nous avons l'ordinateur personnel pour vous.</center><br>   		  		
   				<span class="hiTextBlueS"><center><?=@$param['adresse_client'];?>, <?=@$param['ville_client'];?>, <?=@$param['province_client'];?> <?=@$param['codepostal_client'];?></center></span>
   				<span class="GrosTexte"><center><?=@$param['telephone_client'];?></center></span>
   				<span class="hiTextBlue"><center>Montréal : 514-500-1533</center></span>
   				</td>
  				<!-- td width=20%> avce td a 20 60 pour le 30 70
  				<span class="produits_img">
				  <img src='images/sapin.jpg' alt='Joyeuse fêtes' width="183" height="210" align="left" />
				</span>
				</td -->
				
   			</tr>
  				<td colspan=2 align=right> 
					<div class="fb-like" data-href="https://www.facebook.com/pages/Cosat-Informatique/454146964701973#!/pages/Cosat-Informatique/454146964701973" 
					data-width="500"
					data-layout="standard" data-action="like" data-show-faces="true" data-share="true">
					</div>				
				</td>
 			<tr>
   			</tr>
   		</table>
   	</div>
  </div>
