<?php
?>
  <div id="advert">
  		<table>
  			<tr>
  				<td width=30% >
  				<span class="produits_img">
				  <img src='images/atemps.jpg' width="116" height="109" align="left" />
				</span>
				</td>
				<td width=40%>

				<span class="GrosTexte"><center>LIVRAISON RAPIDE!!!</center></span>
		
   				<center>
   				Vous cherchez une pièce<br>
   		  		Si nous ne l'avons pas en stock,</center>
   				<span class="hiTextBlue"><center>Nous pouvons vous la procurer la plupart du temps en 24 heures</center></span>
   				</td>
   				<td width=30% >
  				<span class="produits_img">
				  <img src='images/livraison.jpg' width="116" height="101" align="right" />
				</span>
				</td>
  			</tr>
   		</table>
  </div>
