<?php
	// Portion BODY
?>
<!-- body_text //-->
    <td width="80%" valign="top">
	<table border="0" width="80%" cellspacing="0" cellpadding="0">
      <tr>
        <td>
		  	<table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tr>
            <td><img src="gifs/pixel_trans.gif" border="0" alt="" width="100%" height="2"></td>
          </tr>
          <tr>
            <td>
        		<!-- Encadré //-->
		<table border="0" width="80%" cellspacing="0" cellpadding="0">
		  <tr>
			<td class="s_plan_b">
		      	  PROMO QR CODE
		        </td>
		  </tr>
		</table>

<table border="0" width="80%" cellspacing="0" cellpadding="1">
	<tr>
		<td>
			<table border="2" width="100%" cellspacing="1" cellpadding="4" >
         <tr>
            <td><img src="gifs/pixel_trans.gif" border="0" alt="" width="100%" height="2"></td>
          </tr>
				<tr>
					<td>
					<font color='#df0224' size=+2 >Imprimez et apportez cette page et vous aurez droit à un rabais de 10% sur pièces en magasin. 5% sur ordinateurs neufs et 15% sur ordinateurs reconditionnés</font>
 					</td>
				</tr>
         <tr>
            <td><img src="gifs/pixel_trans.gif" border="0" alt="" width="100%" height="2"></td>
          </tr>
			</table>
		</td>
	</tr>
</table>
<!-- encadré_eof //-->
				</td>
          </tr>
          <tr>
            <td><img src="gifs/pixel_trans.gif" border="0" alt="" width="80%" height="10"></td>
          </tr>
        </table>
		  </td>
      </tr>
    </table>
	</td>
<!-- body_text_eof //-->