<?php
/* Programme : CliMessEn.Inc
* Description : Tableau pour la traduction contenant les mots et phrases de la section client
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/
$TabId = array (
	   1 => "<title>Añadir Categoría</title>",
	   2 => "<title>Buscar Categoría</title>",
	   3 => "<title>Consultación del Categoría</title>", 
	   4 => "", 
	   5 => "SISTEMA TRATAMIENTO DEL CATEGORÍA",
	   6 => "Código",
	   7 => "Padre",
	   8 => "Fin",
	   9 => "Título Francés",
	   10 => "Título Inglés",
	   11 => "Título Español",
	   12 => "Markup",
	   13 => "Online",
	   36 => "Quitar",
	   39 => "Adición", 
	   40 => "Buscar", 
	   41 => "Modificar",
	   44 => "Tarifa",
	   45 => "Ver Tarifa",
	   46 => "Imprimir",
	   48 => "Suprimir",
	   49 => "AÑADIR A UN CATEGORÍA", 
	   50 => "BUSCAR A UN CATEGORÍA", 
	   51 => "CONSULTA A UN CATEGORÍA", 
	   52 => "",
	   53 => "",
	   54 => "Lista",
	   55 => "Reporte",
	   60 => "Añadiendo Categoría alcanzamos",
	   61 => "EL CATEGORÍA SE INSERTE CON EXITO.<br>  NÚMERO IS <br>",
	   70 => "Introduzca la información que añadir.",
	   71 => "Introduzca las informaciones antes de la consulta.",
);
?>
