<?php
/* Programme : CliMessEn.Inc
* Description : Tableau pour la traduction contenant les mots et phrases de la section client
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/
$TabId = array (
	   1 => "<title>Adding category record</title>",
	   2 => "<title>Finding category record</title>",
	   3 => "<title>Consult category record</title>", 
	   4 => "", 
	   5 => "CATALOG PROCESSING SYSTEM",
	   6 => "Id",
	   7 => "Parent",
	   8 => "Order",
	   9 => "French Title",
	   10 => "English Title",
	   11 => "Spanish Title",
	   12 => "Markup",
	   13 => "Online",
	   36 => "Quit",
	   39 => "Add", 
	   40 => "Find", 
	   41 => "Modification",
	   44 => "Tarification",
	   45 => "See Tarif.",
	   46 => "Print",
	   48 => "Delete",
	   49 => "CATEGORY ENTRY", 
	   50 => "SEARCHING A CATEGORY", 
	   51 => "CATEGORY CONSULTING", 
	   54 => "List",
	   55 => "Report",
	   60 => "Adding category succeed",
	   61 => "THE CATEGORY WAS INSERT WITH SUCCESS.<br>IS NUMBER IS<br>",
	   70 => "Enter the informations to add.",
	   71 => "Enter the informations fore the search.",
);
?>
