<?php
/* Programme : CliMessFR.Inc
* Description : Tableau pour la traduction contenant les mots et phrases de la section client
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/
$TabId = array (
	   1 => "<title>Ajout d'une categorie</title>",
	   2 => "<title>Recherche d'une categorie</title>",
	   3 => "<title>Consultation d'une categorie</title>", 
	   4 => " ", 
	   5 => "SYSTÈME DE TRAITEMENT CATALOGUE",
	   6 => "Id",
	   7 => "Parent",
	   8 => "Ordre",
	   9 => "Titre français",
	   10 => "Titre anglais",
	   11 => "Titre espagnol",
	   12 => "Markup",
	   13 => "Online",
	   36 => "Quitter",
	   39 => "Ajouter", 
	   40 => "Rechercher", 
	   41 => "Modifier",
	   44 => "Tarif",
	   45 => "Voir Tarif",
	   46 => "Imprimer",
	   48 => "Détruire",
	   49 => "AJOUT D'UNE CATÉGORIE", 
	   50 => "RECHERCHE D'UNE CATÉGORIE", 
	   51 => "CONSULTATION D'UNE CATÉGORIE", 
	   52 => "",
	   53 => "",
	   54 => "Liste",
	   55 => "Rapport",
	   60 => "Catégorie ajouter avec succès",
	   61 => "CATÉGORIE AJOUTER AVEC SUCCÈS.<br>SON NUMÉRO EST LE<br>",
	   70 => "Entrez les informations de la catégorie à ajouter.",
	   71 => "Entrez les informations de la catégorie recherchée.",
);
?>
