<?php
/* Fichier : logtabsp.inc
* Description : Tableau des messages et texte divers de la page des logins
* 			    Un fichier existe pour le francais, l'anglais, l'espagnol 
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/

$TabId = array (
	   1 => "<title>Cosat Extranet Home Page</title>",
	   2 => " Restricted Are  ",
	   3 => "Are you already a customer ?",
	   4 => "Login",
	   5 => "Password",
	   6 => "Enter !",
	   7 => "Quit",
	   8 => "This function will be available soon.<br>Tank for your patience.",
	   9 => "Want to be one of our customer ?",
	   10 => "Secur services for all your needs. Everywhere in the world ",
	   11 => " is here. Package shipping, Money transfert, Send gift to your family.
	   	     You can follow your shipping online with our Web site.
			 Let us give you more information right now. Just complete de following form.
         	 One of our representative will communicate with you. Or simply call us at ",
	   12 => ". Absolutly No obligation from your part.",
	   13 => "Name",
	   14 => "First name",
	   15 => "City",
	   16 => "Country",
	   17 => "E-Mail",
	   18 => "Phone",
	   19 => "Fax",
	   20 => "Registration !",
	   30 => " Search on name : ",
	   31 => " Search on password : ",
	   32 => "Can't add to login",
	   33 => "INVALID PASSWORD FOR ",
	   34 => "INVALID Identification! Try again.",
);
?>
