<?php
/* Fichier : logtabsp.inc
* Description : Tableau des messages et texte divers de la page des logins
* 			    Un fichier existe pour le francais, l'anglais, l'espagnol 
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/

$TabId = array (
	   1 => "<title>Page d'acceuil Extranet Cosat</title>",
	   2 => " Accès Restreint ",
	   3 => "Êtes-vous déjà clients ?",
	   4 => "Nom de login",
	   5 => "Mot de passe",
	   6 => "Identifiez-vous !",
	   7 => "Quitter",
	   8 => "Cette fonction sera bientôt disponible.<br>Merci de votre patience.",
	   9 => "Pas encore client ?",
	   10 => "Des services sécuritaire pour tout vos besoins. Partout dans le monde ",
	   11 => " est là. Envoi de Colis, Transfert de fonds, Cadeau à distance, 
	   	     Communication téléphonique. La possibilité de suivre vos envois en ligne sur 
			 Internet. Informez-vous dès maintenant en remplissant le formulaire.
         	 Un de nos préposés communiquera avec vous. Ou simplement téléphoner au ",
	   12 => ". Aucun engagement de votre part.",
	   13 => "Nom",
	   14 => "Prénom",
	   15 => "Ville",
	   16 => "Pays",
	   17 => "Courriel",
	   18 => "Téléphone",
	   19 => "Fax",
	   20 => "Enregistrez-vous !",
	   30 => " Requête sur nom : ",
	   31 => " Requête sur password : ",
	   32 => "Impossible d'exécuter l'Ajout Login",
	   33 => "Mot de passe INVALIDE pour ",
	   34 => "Identification INVALIDE. Essayez encore.",
);
?>
