<?php
/* Programme : CliMessFR.Inc
* Description : Tableau pour la traduction contenant les mots et phrases de la section client
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/
$TabId = array (
	   1 => "<title>Add a devise</title>",
	   3 => "<title>Consult a devise</title>",
	   4 => "<title>Votre dossier Client</title>", 
	   5 => "DEVISE TRAITEMENT SYSTEM",
	   6 => "Devise",
	   7 => "TauxVenteUS",
	   8 => "Transfert",
	   9 => "Paiement",
	   10 => "TauxAchatUS",
	   11 => "Symbole",
	   12 => "Commentaire",
	   13 => "Old tx",
	   14 => "Frais",
	   36 => "Quitter",
	   39 => "Ajouter", 
	   41 => "Modifier",
	   46 => "Imprimer",
	   48 => "Détruire",
	   49 => "ADD A DEVISE",
	   51 => "CONSULT A DEVISE",
	   60 => "Devise ajouter avec succès",
	   61 => "DEVISE AJOUTER AVEC SUCCÈS.<br>SON NUMÉRO EST LE<br>",
	   70 => "Entrez les informations de la devise à ajouter.",
);
?>
