<?php
/* Programme : MSMessFR.Inc
* Description : Tableau pour la traduction contenant les mots et phrases de la section Sécurité
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/

$TabMessSecur = array (
	   1 => "Page d'Erreur de la sécurité",
	   2 => "Accès Sécurité impossible",
	   3 => "Sécurité",
	   4 => "Login",
	   5 => "Mot de passe",
	   6 => "Priorité",
	   7 => "Création",
	   8 => "Langue",
	   9 => "Client",
	   10 => "SYSTÈME DE TRAITEMENT DES USAGERS",
	   11 => "Consultation Sécurité",
	   12 => "Ajout d'un Usager",
	   13 => "AJOUT D'UN USAGER",
	   14 => "Consultation d'un Usager",
	   15 => "CONSULTATION D'UN USAGER",
	   16 => "Recherche d'un Usager",
	   17 => "RECHERCHE D'UN USAGER",
	   20 => "CHANGEMENT DU MOT DE PASSE",
	   21 => "Nouveau mot de passe",
	   22 => "Confirmation du mot de passe",
	   23 => "Vous devez maintenant changer votre mot de passe. Soit que la date de validation est 
	   	  	 dépassé, soit que c'est la première fois que vous l'utiliser. Choisissez toujours un
			 mot de passe que vous seul connaitrez. Il doit être composé de lettres et de chiffres
			 et avoir au moins 5 caractères.",
	   24 => "Votre mot de passe est invalide. Seulement des lettres et des chiffres S.V.P.",
	   25 => "Vous devez taper au moins 5 caratères.",
	   26 => "Vous avez fait un erreur de confirmation.",
	   27 => "Aucun changement d'effectué ! S.V.P. Recommencez.",
	   28 => "Page de changement de mot de passe.",
	   90 => "Page d'erreur - USAGER",
	   91 => "Accès USAGER impossible",
	   92 => "Consultation des Usagers",
	   93 => "Liste des Usagers",
	   94 => "Aucun Usager de défini",
	   95 => "Cet Usager existe déjà."	   
	   
);
?>
