<?php
/* Programme : MSMessSP.Inc
* Description : Tableau pour la traduction contenant les mots et phrases de la section Sécurité
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/

$TabMessSecur = array (
	   1 => "Página de Error de seguridad",
	   2 => "Seguridad Acceso imposible",
	   3 => "Seguridad",
	   4 => "Registro",
	   5 => "Clave de acceso",
	   6 => "Prioridad",
	   7 => "Creación",
	   8 => "Idioma",
	   9 => "Clientes",
	   10 => "SISTEMA TRATAMIENTO DE USUARIO",
	   11 => "Consulta de Seguridad",
	   12 => "Agregar un Usuario",
	   13 => "AGREGAR UN USUARIO",
	   14 => "Consultation d'un Usager",
	   15 => "CONSULTATION D'UN USAGER",
	   16 => "Recherche d'un Usager",
	   17 => "RECHERCHE D'UN USAGER",
	   20 => "CAMBIO DE CLAVE DE ACCESO",
	   21 => "Nueva clave de acceso",
	   22 => "Confirmación de clave de acceso",
	   23 => "Usted debe cambiar su clave de acceso ahora, debido a que ha expirado o 
	   	  	 que es la primera vez que la utiliza. Escoja siempre una clave de acceso
			 que sólo Usted pueda reconocer. Debe estar compuesta de letras y números
			 y tener al menos 5 caracteres.",
	   24 => "Su clave de acceso es inválida. Sólo puede utilizar letras y números.",
	   25 => "Debe ingresar al menos 5 caracteres.",
	   26 => "Error de confirmación.",
	   27 => "Ningún cambio efectuado. Por favor comience nuevamente.",
	   28 => "Página de cambio de clave de acceso.",
	   90 => "Página de Error de Usuario",
	   91 => "USUARIO Accesso imposible",
	   92 => "Consulta de Usuario",
	   93 => "User List",
	   94 => "No USER define",
	   95 => "This user name already exist."	   
	   
);
?>
