<?php
/* Programme : MSMessEN.Inc
* Description : Tableau pour la traduction contenant les mots et phrases de la section Sécurité
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/

$TabMessSecur = array (
	   1 => "Security - Error Page",
	   2 => "No Access to the security table",
	   3 => "Security",
	   4 => "Login",
	   5 => "Password",
	   6 => "Priority",
	   7 => "Creation",
	   8 => "Language",
	   9 => "Customer",
	   10 => "USER'S TRAITEMENT SYSTEM",
	   11 => "Security consultation",
	   12 => "Adding a user",
	   13 => "ADDING A USER",
	   20 => "CHANGE PASSWORD PAGE",
	   21 => "New password",
	   22 => "Confirm password",
	   23 => "Now you have to chage your password. It the first type you use it or your account
	   	      has expired. Please, choose a new password that will be know only by you. It should
			  have letter and number and 5 characters minimum.",
	   24 => "Your password is invalid. Please ! Type letter and number only.",
	   25 => "Ypou have type less than 5 character.",
	   26 => "Your confirmation is INVALID.",
	   27 => "No change made. Keep trying.",
	   28 => "Changing Password Page.",
	   90 => "USER - Error Page",
	   91 => "No USER Access",
	   92 => "User Consultation",
	   93 => "User List",
	   94 => "No USER define",
	   95 => "This user name already exist."	   
	   
);
?>
