<?php
/* Programme : CliGlobal.Inc
* Description : Description des variables globales de la section client.
* Auteur : Denis Léveillé 	 		  Date : 2004-01-01
*/
global $do,$id,$titre_fr,$titre_en, $titre_sp, $prix_detail, $prix_promo, $id_devise, 
		$Code, $Cout, $Markup, $QteStock, $QteVendu, $QteCmd, $QteBO, $QteDOA, $Unité, $weight, $width, $height, 
		$description_fr, $description_en, $description_sp,$description_supplementaire_fr, 
		$description_supplementaire_en, $description_supplementaire_sp, $small, $medium, $big, 
		$Secteur_Limite, $Qte_Max_Livre, $online, $Provenance, $TabMessGen, $TabId;
?>