<?php
/* Auteur : Denis Léveillé 	 		  Date : 2004-01-01 */


$NomChamps = array(
		"id"=>"Identification du produit",
		"titre_fr"=>"Titre Francais",
		"titre_en"=>"English title", 
		"titre_sp"=>"Titre espagnol", 
		"prix_detail"=>"Prix de vente au détail", 
		"prix_promo"=>"Prix de vente en promotion", 
		"Code"=>"Code du fournisseur", 
		"Cout"=>"Cout du produit", 
		"Markup"=>"% de profit sur item", 
		"id_devise"=>"Numéro de la devise", 
		"weight"=>"Poid pour livraison", 
		"width"=>"Largeur du produits", 
		"height"=>"Hauteur du produit", 
		"description_fr"=>"Description en francais", 
		"description_en"=>"English Description", 
		"description_sp"=>"Description en francais",
		"description_supplementaire_fr"=>"Description supplémentaire", 
		"description_supplementaire_en"=>"Supplemental description", 
		"description_supplementaire_sp"=>"Description supplémentaire",
		"QteStock"=>"Description supplémentaire",            
		"QteVendu"=>"Description supplémentaire",           
		"QteCmd"=>"Description supplémentaire",           
		"QteBO"=>"Description supplémentaire",             
		"QteDOA"=>"Description supplémentaire",            
		"Provenance"=>"Le pays d'ou provient le produit",            
		"Unité"=>"Description supplémentaire",              
 		"Ok"=>"Ok");
?>